use serde::Deserialize;

#[derive(Deserialize)]
#[cfg_attr(feature = "strict_json_fields", serde(deny_unknown_fields))]
#[serde(rename_all = "PascalCase")]
pub struct RoleSkinData {
    pub id: i32,
    pub role_id: i32,
    pub suit_weapon_skin_id: i32,
    pub head_id: i32,
    pub quality_id: i32,
    pub name: String,
    pub title_name: String,
    pub sub_dec_name: String,
    pub type_description: String,
    pub attributes_description: String,
    pub bg_description: String,
    pub icon_middle: String,
    pub icon_small: String,
    pub item_access: Vec<i32>,
    pub sort_index: i32,
    pub red_dot_disable_rule: i32,
    pub show_in_bag: bool,
    pub obtained_show_description: String,
    pub icon: String,
    pub function_desc: String,
    pub first_obtain_desc: String,
    pub quality: u8,
    pub tag: String,
    pub role_head_icon_circle: String,
    pub role_head_icon_large: String,
    pub role_head_icon_big: String,
    pub card: String,
    pub role_head_icon: String,
    pub preview_role_card: String,
    pub buy_shop_preview_role_card: String,
    pub formation_role_card: String,
    pub role_stand: String,
    pub suit_weapon_skin_color: String,
    pub role_obtain_color1: String,
    pub role_obtain_color2: String,
    pub role_portrait: String,
    pub mesh_id: i32,
    pub ui_mesh_id: i32,
    pub role_body: String,
    #[serde(rename = "UiScenePerformanceABP")]
    pub ui_scene_performance_abp: String,
    pub foot_step_state: String,
    pub pay_shop_preview_role_texture_path: String,
    pub pay_shop_preview_role_texture_bg_path: String,
    pub pay_shop_preview_weapon_texture_path: String,
    pub pay_shop_preview_buy_role_texture_path: String,
    pub pay_shop_preview_buy_role_suit_weapon_texture_path: String,
    pub share_texture_path: String,
    pub spine_skeleton_data: String,
    pub small_spine_atlas: String,
}
